import { describe, expect, it } from "vitest";
import { replaceManagedMocIndex } from "../src/organizer/managed-moc.js";

const start = "<!-- brain-auto:start note-index -->";
const end = "<!-- brain-auto:end note-index -->";

describe("managed MOC replacement", () => {
  it("replaces only managed bytes and stable-sorts links by normalized path", () => {
    const before = "# Human title\n설명은 그대로.\n";
    const after = "\n## Human footer\n그대로 끝.\n";
    const existing = `${before}${start}\nold generated bytes\n${end}${after}`;

    const rendered = replaceManagedMocIndex(existing, [
      { path: "20_Study/zeta.md", title: "제타" },
      { path: "20_Study/Alpha.md", title: "알파" },
    ]);

    expect(rendered).toBe(`${before}${start}\n- [[20_Study/Alpha.md|알파]]\n- [[20_Study/zeta.md|제타]]\n${end}${after}`);
    expect(rendered.slice(0, rendered.indexOf(start))).toBe(before);
    expect(rendered.slice(rendered.indexOf(end) + end.length)).toBe(after);
    expect(replaceManagedMocIndex(rendered, [
      { path: "20_Study/zeta.md", title: "제타" },
      { path: "20_Study/Alpha.md", title: "알파" },
    ])).toBe(rendered);
  });

  it("uses the marker's CRLF style without changing surrounding bytes", () => {
    const existing = `before\r\n${start}\r\nold\r\n${end}\r\nafter\r\n`;
    expect(replaceManagedMocIndex(existing, [{ path: "20_Study/a.md", title: "A" }])).toBe(
      `before\r\n${start}\r\n- [[20_Study/a.md|A]]\r\n${end}\r\nafter\r\n`,
    );
  });

  it.each([
    ["missing", "human text only"],
    ["duplicate", `${start}\na\n${end}\n${start}\nb\n${end}\n`],
    ["nested", `${start}\n${start}\n${end}\n${end}\n`],
    ["reversed", `${end}\n${start}\n`],
    ["malformed indentation", ` ${start}\nold\n${end}\n`],
  ])("fails closed for %s markers", (_name, existing) => {
    expect(() => replaceManagedMocIndex(existing, [])).toThrow(/managed marker/i);
  });

  it("rejects unsafe paths and case-insensitive or Unicode-equivalent collisions", () => {
    const existing = `${start}\nold\n${end}\n`;
    expect(() => replaceManagedMocIndex(existing, [{ path: "../escape.md", title: "bad" }])).toThrow(/path/i);
    expect(() => replaceManagedMocIndex(existing, [
      { path: "20_Study/A.md", title: "A" },
      { path: "20_Study/a.md", title: "a" },
    ])).toThrow(/collision|ambiguous/i);
    expect(() => replaceManagedMocIndex(existing, [
      { path: "20_Study/é.md", title: "one" },
      { path: "20_Study/e\u0301.md", title: "two" },
    ])).toThrow(/collision|ambiguous/i);
  });

  it("escapes a supplied display title without allowing a second link or line", () => {
    const existing = `${start}\nold\n${end}\n`;
    const rendered = replaceManagedMocIndex(existing, [{
      path: "20_Study/safe.md",
      title: "safe]] | [[evil\n# injected",
    }]);

    expect(rendered.match(/\[\[/g)).toHaveLength(1);
    expect(rendered).not.toContain("\n# injected");
    expect(rendered).toContain("safe&#93;&#93; &#124; &#91;&#91;evil # injected");
  });
});
